print("=="*25)
print(" INPUT BIODATA ".center(50,"#"))
print("=="*25)
nama = input("Masukkan Nama Anda = ")
alamat = input("Maukkkan Alamat Anda = ")
agama = input("Masukkan agama Anda = ")
tinggi = input("Masukkan Tinggi Anda = ")
berat = input("Masukkan Berat Anda = ")
umur = input("Masukkan Umur Anda = ")
no = input("Masukkan Nomer Hp Anda = ")
email = input("Masukkan Email Anda = ")
sd = input("Masukkan Data Pendidikan SD = ")
smp = input("Masukkan Data Pendidikan SMP = ")
sma = input("Masukkan Data Pendidikan SMA = ")
pt = input("Masukkan Data Pendidikan Perguruan Tinggi = ")

print("=="*25)
print("CURRICULUM VITAE".center(50,"-"))
print("=="*25)
print("Hallo nama saya ".ljust(25) + ":",nama)
print("saya berasa dari ".ljust(25) + ":", alamat)
print("saya beragama ".ljust(25) + ":",agama)
print("tinggi saya adalah ".ljust(25) + ":",tinggi + " cm")
print("berat badan saya ".ljust(25) + ":",berat + " kg")
print("umur saya adalah ".ljust(25) + ":",umur + " tahun")
print("No Hp ".ljust(25) + ":",no)
print("email ".ljust(25) + ":",email)
print("=="*25)
print("Sekolah Dasar ".ljust(25) + ":",sd)
print("SMP ".ljust(25) + ":",smp)
print("SMA ".ljust(25) + ":",sma)
print(" Perguruan Tinggi ".ljust(25) + ":",pt)
print("=="*25)